from aray import *
print("--------LIST--------")
print("")
l=[12,13,-5,0,8,'python',"CO"]
print("printing original list",l)
print("printing first three elements of list",l[0:3])
print("printing last element of list",l[-1])
print("printing first three elements of list twice",l[0:3]*2)
l1=list(range(1,8))
print("list of range 1 to 7",l1)
l1.sort(reverse =true)
print("descending sort",l1)
l1.sort()
print("ascending sort",l1)
l1.reverse()
print("reverse",l1)
l1.sort()
l1.remove(9)
print("remove 9",l1)
